# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: '2'

run:
  timeout: 3m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: standard
