/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type Office365ExchangeCustomCategoryCondition struct {
	// Exchange custom category rule name.
	RuleName string `json:"ruleName"`
	// Operator of the custom category condition.
	RuleOperator string `json:"ruleOperator"`
	// Value of the custom category condition rule.
	RuleValue string `json:"ruleValue"`
}
