/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Details of locations
type LocationsDetails struct {
	// id of the location
	Id int32 `json:"id,omitempty"`
	// name of the location
	Name string `json:"name,omitempty"`
	// Tells if this is a transit location
	IsTransit bool `json:"isTransit,omitempty"`
}
