/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type UpdateArchivePlanBackupDestination struct {
	// New name for backup destination
	NewName string `json:"newName,omitempty"`
	SourceCopy *IdName `json:"sourceCopy,omitempty"`
	// Tells if this copy has data aging enabled
	EnableDataAging bool `json:"enableDataAging,omitempty"`
	// Retention period in days. -1 can be specified for infinite retention.
	RetentionPeriodDays int32 `json:"retentionPeriodDays,omitempty"`
	// Tells if this copy should use storage pool retention period days or the retention defined for this copy. Set as true to use retention defined on this copy.
	OverrideRetentionSettings bool `json:"overrideRetentionSettings,omitempty"`
}
