/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type EntitySettingsValue struct {
	// Value set for the specified setting linked to the specified entity
	Value string `json:"value,omitempty"`
	// Comment set by user while modifying the specified entity setting for the given entity
	Comment string `json:"comment,omitempty"`
	Entity *IdNameType `json:"entity,omitempty"`
}
