/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of media tracked by vault tacker
type GetVaultTrackerMediaDetailsResp struct {
	VaultTrackerMediaDetailsList []VaultTrackerMediaDetails `json:"vaultTrackerMediaDetailsList,omitempty"`
}
