/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Frequency of replication
type Rpo struct {
	// Max amount of time for which data can be lost during a service disruption. Determines frequency of backup jobs in minutes
	ReplicationFrequency int32 `json:"replicationFrequency,omitempty"`
}
