/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CreateHypervisorGroupDocker struct {
	HypervisorType string `json:"hypervisorType"`
	// Docker hostname 
	ServerName string `json:"serverName"`
	// Docker userName 
	UserName string `json:"userName"`
	// Docker password 
	Password string `json:"password"`
	// The name of the hypervisor group being created
	Name string `json:"name"`
	// if credential validation has to be skipped.
	SkipCredentialValidation bool `json:"skipCredentialValidation,omitempty"`
	AccessNodes []AccessNodeModel `json:"accessNodes,omitempty"`
	Credentials *IdName `json:"credentials,omitempty"`
	EtcdProtection *EtcdProtectionItem `json:"etcdProtection,omitempty"`
	PlanEntity *IdName `json:"planEntity,omitempty"`
}
