/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of index servers
type IndexServersListResp struct {
	IndexServers []IndexServerSummary `json:"indexServers,omitempty"`
}
