/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// SourceHypervisor is the hypervisor that has the VM's to be backed up. This should be already configured. Recovery target contains the replication options that will be applied to the selected VM's. This should be already configured. ID is mandatory for sourceHypervisor and recovery target. Provide both the id and the name for the storage and the vms.
type CreateReplicationGroup struct {
	// The name of the replication group being created
	Name string `json:"name"`
	SourceHypervisor *IdName `json:"sourceHypervisor"`
	// A list of name and GUID of all the virtual machines that have to be replicated
	Vms []NameGuid `json:"vms"`
	// The field denotes the frequency of replication.
	FrequencyInMinutes int32 `json:"frequencyInMinutes,omitempty"`
	RecoveryTarget *IdName `json:"recoveryTarget"`
	// The primary and an optional secondary storage that will be used for storing the source VM data for replication. The secondary storage if provided, will be the default source for replication.
	Storage []StorageCopyCreate `json:"storage"`
}
