/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Request definition for creating Kubernetes cluster
type UpdateKubernetesClusterRequest struct {
	AccessNodes []IdNameType `json:"accessNodes,omitempty"`
	// Name of the Kubernetes Cluster
	Name string `json:"name,omitempty"`
	ServiceType *KubernetesServiceTypes `json:"serviceType,omitempty"`
	EtcdProtection *GetEtcdProtectionItem `json:"etcdProtection,omitempty"`
	// Modify or add tags on the cluster
	Tags []NameValue `json:"tags,omitempty"`
	Region *IdName `json:"region,omitempty"`
	ActivityControl *EditClusterActivityControlOptions `json:"activityControl,omitempty"`
	Options *EditClusterAdvancedOptionsInfo `json:"options,omitempty"`
	// API Server Endpoint of the cluster
	ApiServer string `json:"apiServer,omitempty"`
	// Name of the Service Account to authenticate with the cluster
	ServiceAccount string `json:"serviceAccount,omitempty"`
	// Secret token to authenticate with the cluster
	ServiceToken string `json:"serviceToken,omitempty"`
}
