/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// List of running jobs
type GetRunningJobsIdList struct {
	JobIds []int64 `json:"jobIds,omitempty"`
}
