/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type DiskConfiguration struct {
	// Name of the disk
	Name string `json:"name,omitempty"`
	// Disk provisioning type
	ProvisioningType string `json:"provisioningType,omitempty"`
	// Disk size in bytes
	DiskSize int64 `json:"diskSize,omitempty"`
	// Type of disk controller
	DiskType string `json:"diskType,omitempty"`
}
