/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient
// TapeMediaOperationType : Tape media operation type value
type TapeMediaOperationType string

// List of TapeMediaOperationType
const (
	DISCOVER_MEDIA_TapeMediaOperationType TapeMediaOperationType = "DISCOVER_MEDIA"
	MARK_MEDIA_GOOD_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_GOOD"
	MARK_MEDIA_BAD_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_BAD"
	MARK_MEDIA_FULL_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_FULL"
	MARK_MEDIA_ERASABLE_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_ERASABLE"
	MARK_MEDIA_APPENDABLE_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_APPENDABLE"
	MARK_MEDIA_REUSABLE_TapeMediaOperationType TapeMediaOperationType = "MARK_MEDIA_REUSABLE"
	PREVENT_MEDIA_REUSE_TapeMediaOperationType TapeMediaOperationType = "PREVENT_MEDIA_REUSE"
	ALLOW_MEDIA_REUSE_TapeMediaOperationType TapeMediaOperationType = "ALLOW_MEDIA_REUSE"
	QUICK_ERASE_SELECTED_MEDIA_TapeMediaOperationType TapeMediaOperationType = "QUICK_ERASE_SELECTED_MEDIA"
	FULL_ERASE_SELECTED_MEDIA_TapeMediaOperationType TapeMediaOperationType = "FULL_ERASE_SELECTED_MEDIA"
	DELETE_MEDIA_TapeMediaOperationType TapeMediaOperationType = "DELETE_MEDIA"
	DELETE_CONTENTS_TapeMediaOperationType TapeMediaOperationType = "DELETE_CONTENTS"
	UPDATE_BARCODE_TapeMediaOperationType TapeMediaOperationType = "UPDATE_BARCODE"
	MOVE_MEDIA_TapeMediaOperationType TapeMediaOperationType = "MOVE_MEDIA"
)
