/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Users or User Groups associated with the plan
type PlanUserOrGroups struct {
	// This gives Id of user or user group or external user group
	Id int32 `json:"id,omitempty"`
	// This gives name of user or user group or external user group
	Name string `json:"name,omitempty"`
	Type_ *UserOrGroupsType `json:"type,omitempty"`
	// If set to true, will send an invite email to the user or group. Default is true.
	SendInvite bool `json:"sendInvite,omitempty"`
}
