/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ShelfDetails struct {
	// shelf type.
	Type_ int32 `json:"type,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
