/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CreateEtcdSubclientResp struct {
	SubclientId int32 `json:"subclientId,omitempty"`
	ErrorCode int32 `json:"errorCode,omitempty"`
	// Response message
	ErrorMessage string `json:"errorMessage,omitempty"`
}
