/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// FileServerStatus : Gives the status of the file server.
type FileServerStatus string

// List of FileServerStatus
const (
	OFFLINE_FileServerStatus FileServerStatus = "OFFLINE"
	ONLINE_FileServerStatus FileServerStatus = "ONLINE"
	UNKNOWN_FileServerStatus FileServerStatus = "UNKNOWN"
	NOT_APPLICABLE_FileServerStatus FileServerStatus = "NOT_APPLICABLE"
)
