/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of all Kubernetes Clusters
type GetClusterResp struct {
	// Total number of clusters
	ClusterCount int32 `json:"clusterCount,omitempty"`
	Clusters []KubernetesClusterItem `json:"clusters,omitempty"`
}
