/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Gateway information for network topology
type GatewayConnectionInfo struct {
	// Gateway machine hostname
	Hostname string `json:"hostname,omitempty"`
	Port int32 `json:"port,omitempty"`
}
