/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type LaptopsWebConsole struct {
	// id of the laptop client
	Id int32 `json:"id,omitempty"`
	// name of the laptop client
	Name string `json:"name,omitempty"`
	// This specifies the last backup time (in unix timestamp)
	LastBackupTime int32 `json:"lastBackupTime,omitempty"`
	LastBackupJobInfo *LastBackupJobInfo `json:"lastBackupJobInfo,omitempty"`
	// This specifies the total backup size (in bytes)
	TotalBackupSize int32 `json:"totalBackupSize,omitempty"`
	// This species the timestamp (in unix timestamp) of the next scheduled backup
	NextBackupTime int32 `json:"nextBackupTime,omitempty"`
	SlaStatus *SlaStatus `json:"slaStatus,omitempty"`
	// reason for the current sla status
	SlaReason string `json:"slaReason,omitempty"`
}
