/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type Office365SharepointCustomCategoryReq struct {
	// Name of the custom category.
	Name string `json:"name"`
	Office365Plan *IdName `json:"office365Plan"`
	Conditions []Office365SharepointCustomCategoryCondition `json:"conditions"`
}
