/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CompanyStatus struct {
	// Used to activate or deactivate the company. Not applicable for SaaS.
	Deactivate bool `json:"deactivate,omitempty"`
	Options *DeactivationOptions `json:"options,omitempty"`
}
