/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient
// ContentIndexingOperationType : Describes the Content Indexing Operation Type for Data Classification Plan
type ContentIndexingOperationType string

// List of ContentIndexingOperationType
const (
	METADATA_ContentIndexingOperationType ContentIndexingOperationType = "METADATA"
	METADATA_CONTENT_ContentIndexingOperationType ContentIndexingOperationType = "METADATA_CONTENT"
	METADATA_CONTENT_PREVIEW_ContentIndexingOperationType ContentIndexingOperationType = "METADATA_CONTENT_PREVIEW"
)
