/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ServerOrServerGroupTypes string

// List of ServerOrServerGroupTypes
const (
	SERVER_ServerOrServerGroupTypes ServerOrServerGroupTypes = "SERVER"
	SERVER_GROUP_ServerOrServerGroupTypes ServerOrServerGroupTypes = "SERVER_GROUP"
)
