/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Inventory response of hypervisor for Network entity
type NetworkInventoryResponse struct {
	// dataCenter Name of the Network.
	DataCenterName string `json:"dataCenterName,omitempty"`
	// dns Hostname  of the Network.
	DnsHostName string `json:"dnsHostName,omitempty"`
	// esx server name  of the Network.
	EsxServerName string `json:"esxServerName,omitempty"`
	NetworkSettings []IdName `json:"networkSettings,omitempty"`
}
