/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Gives summary of replication group.
type ReplicationMonitorDetailSummary struct {
	// Id of replication pair
	Id int32 `json:"id,omitempty"`
	Source *IdName `json:"source,omitempty"`
	Destination *IdName `json:"destination,omitempty"`
	// Gives information about the recovery type of replication group
	RecoveryType string `json:"recoveryType,omitempty"`
	// Gives information about the synchronization status
	SynchronizationStatus string `json:"synchronizationStatus,omitempty"`
	// Lag time in seconds
	ReplicationLag int32 `json:"replicationLag,omitempty"`
	// additional description of current pair status
	EventMessage string `json:"eventMessage,omitempty"`
}
