/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// The response of the continuous replication pair failover request
type ContinuousPairFailoverResponse struct {
	JobId *JobId `json:"jobId,omitempty"`
}
