/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Response structure to get all spare group properties
type GetSpareGroupProperties struct {
	// Name of the spare group
	Name string `json:"name,omitempty"`
	// Spare group type Id
	TypeId int32 `json:"typeId,omitempty"`
	// Low watermark value set for the spare group
	LowWaterMark int32 `json:"lowWaterMark,omitempty"`
	// High watermark value set for the spare group
	HighWaterMark int32 `json:"highWaterMark,omitempty"`
	// Id of default media type selected for spare group
	DefaultMediaTypeId int32 `json:"defaultMediaTypeId,omitempty"`
	// Name of default media type selected for spare group
	DefaultMediaTypeName string `json:"defaultMediaTypeName,omitempty"`
}
