/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Replication options for Azure
type OverrideReplicationOptionsAzure struct {
	// VM availability zone
	AvailabilityZone string `json:"availabilityZone,omitempty"`
	SecurityGroup *SecurityGroup `json:"securityGroup,omitempty"`
	TestFailoverVirtualNetwork *AzureNetwork `json:"testFailoverVirtualNetwork,omitempty"`
	VirtualNetwork *AzureNetwork `json:"virtualNetwork,omitempty"`
}
