/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Summary of a Kubernetes Application
type KubernetesApplicationGroupSummaryInfo struct {
	NextBackupTime int32 `json:"nextBackupTime,omitempty"`
	// Describes if the Application Group is an ETCD Application Group
	IsETCDApplicationGroup bool `json:"isETCDApplicationGroup,omitempty"`
	// Describes if the Application Group is a default Application Group
	IsDefaultApplicationGroup bool `json:"isDefaultApplicationGroup,omitempty"`
	Plan *IdName `json:"plan,omitempty"`
	Timezone *IdName `json:"timezone,omitempty"`
	Tags []IdNameValue `json:"tags,omitempty"`
	Content *KubernetesApplicationGroupContentItem `json:"content,omitempty"`
	Filters *KubernetesApplicationGroupFilterItem `json:"filters,omitempty"`
	LastBackup *LastBackupJobInfo `json:"lastBackup,omitempty"`
	ActivityControl *ApplicationGroupActivityControl `json:"activityControl,omitempty"`
	AccessNodes []IdName `json:"accessNodes,omitempty"`
	Options *ApplicationGroupGetOptions `json:"options,omitempty"`
	Cluster *IdNameDisplayName `json:"cluster,omitempty"`
	Instance *IdName `json:"instance,omitempty"`
	Backupset *IdName `json:"backupset,omitempty"`
}
