/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type VmAppsDiscovered struct {
	// name of the VM apps discovered for validation
	Name string `json:"name,omitempty"`
	// true if validation status is true
	ScriptStatus bool `json:"scriptStatus,omitempty"`
	// reason for failure of validation of app
	FailureReason string `json:"failureReason,omitempty"`
}
