/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type SnapForceReq struct {
	Volumes []SnapVolumes `json:"volumes,omitempty"`
}
