/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type UpdateHypervisorGroupDocker struct {
	HypervisorType string `json:"hypervisorType"`
	// Docker hostname 
	ServerName string `json:"serverName,omitempty"`
	// Docker userName 
	UserName string `json:"userName,omitempty"`
	// Docker password 
	Password string `json:"password,omitempty"`
	AccessNodes []AccessNodeModel `json:"accessNodes,omitempty"`
	FbrUnixMediaAgent *IdName `json:"fbrUnixMediaAgent,omitempty"`
	ActivityControl *ActivityControlOptions `json:"activityControl,omitempty"`
	Security *VmHypervisorSecurityProp `json:"security,omitempty"`
	// The name of the hypervisor that has to be changed
	NewName string `json:"newName,omitempty"`
	Settings *HypervisorSettings `json:"settings,omitempty"`
	Credentials *IdName `json:"credentials,omitempty"`
	// if credential validation has to be skipped.
	SkipCredentialValidation bool `json:"skipCredentialValidation,omitempty"`
}
