/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type RecoveryExpirationOptions struct {
	// If true, cleans up recovered VMs after the set daysToExpire value
	EnableExpirationOption bool `json:"enableExpirationOption,omitempty"`
	// Number of days after which recovered VMs are automatically cleaned up
	DaysToExpire int32 `json:"daysToExpire,omitempty"`
	// Whether the CommServe is rescued or not
	IsRescuedCommServe bool `json:"isRescuedCommServe,omitempty"`
	// Timestamp when the clean up of all recovered VMs happens on the rescued CommServe. It happens 4 hours before the CommServe expiration time
	ExpirationTime int32 `json:"expirationTime,omitempty"`
}
