/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type PsaDiscoverStatus struct {
	Status *PsaCompanyStatusEnum `json:"status,omitempty"`
	// Reason for failure
	Reason string `json:"reason,omitempty"`
}
