/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type SnapCopyInfo struct {
	// True if hardware snapshot is enabled
	EnableHardwareSnapshot bool `json:"enableHardwareSnapshot,omitempty"`
	SnapEngine *IdName `json:"snapEngine,omitempty"`
	// Name of ESX Host
	SnapMountESXHost string `json:"snapMountESXHost,omitempty"`
	// True if independent disk option is enabled
	IsIndependentDisksEnabled bool `json:"isIndependentDisksEnabled,omitempty"`
	// True if raw device maps option is enabled
	IsRawDeviceMapsEnabled bool `json:"isRawDeviceMapsEnabled,omitempty"`
	// True if separate proxy client is used for snap to tape
	UseSeparateProxyForSnapToTape bool `json:"useSeparateProxyForSnapToTape,omitempty"`
	SnapMountProxy *IdName `json:"snapMountProxy,omitempty"`
	// Virtual machine application user name
	VmApplicationUserName string `json:"vmApplicationUserName,omitempty"`
	BackupCopyInterface *BackupCopyInterface `json:"backupCopyInterface,omitempty"`
}
