/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Applicable only for credentials with Cloud Account and Vendor Type as Oracle Infrastructure
type OracleCredentialInfo struct {
	// User Account of Credential
	UserAccount string `json:"userAccount"`
	// Password of Credential. Password must be in base64 encoded format.
	Password string `json:"password"`
	// Connect String for Credential
	ConnectString string `json:"connectString"`
	// DB Name for Credential
	DbName string `json:"dbName"`
	// Certificate of Credential
	Certificate string `json:"certificate"`
	// Oracle Cloud ID
	TenancyOCID string `json:"tenancyOCID"`
	// User name for the Oracle Cloud ID
	UserOCID string `json:"userOCID"`
	// Description of Credential
	Description string `json:"description,omitempty"`
	Security *CredentialSecurity `json:"security,omitempty"`
	AccountType *CredentialAccountType `json:"accountType"`
	VendorType *CloudVendorType `json:"vendorType,omitempty"`
	// Name of Credential
	Name string `json:"name"`
}
