/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// List of schedules
type TaskListResponse struct {
	TaskDetail []TaskDetail `json:"taskDetail,omitempty"`
}
