/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ChangeCommServHostNameReq struct {
	// New hostname for CommServ
	HostName string `json:"hostName,omitempty"`
}
