/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type StorageAssociatedCopies struct {
	// List of copies associated with given storage pool
	Copies []StorageAssociatedCopy `json:"copies,omitempty"`
}
