/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ActiveDirectoryClient struct {
	// Azure Active Directory (139), Granular Active Directory (41) or File Server (33)
	AppTypeId int32 `json:"appTypeId,omitempty"`
	Subclient *IdName `json:"subclient,omitempty"`
	Backupset *IdName `json:"backupset,omitempty"`
	Client *IdNameDisplayName `json:"client,omitempty"`
	Plan *IdName `json:"plan,omitempty"`
	Company *IdNameFullName `json:"company,omitempty"`
	SlaStatus *SlaStatus `json:"slaStatus,omitempty"`
	DomainURL string `json:"domainURL,omitempty"`
	ApplicationSize int64 `json:"applicationSize,omitempty"`
	NumberOfItems int32 `json:"numberOfItems,omitempty"`
	IsConfigured bool `json:"isConfigured,omitempty"`
	IsDisabledClient bool `json:"isDisabledClient,omitempty"`
	UserAccount *IdName `json:"userAccount,omitempty"`
	LastBackup *LastBackupJobInfoWithLastSuccessfulBackup `json:"lastBackup,omitempty"`
	SlaSummary *Office365SlaSummary `json:"slaSummary,omitempty"`
}
