/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Generic template for arrayConfigs
type ArrayConfigsBasic struct {
	// This is the masterConfigId, which is available for each vendor's configs
	MasterConfigId int32 `json:"masterConfigId"`
	// This is the name of the config which is displayed on the Command Center Console
	Name string `json:"name"`
	// Type of the config value. type can accept 7 values [1,2,8,10,12,13,14], 1: boolean, 2: integer, 8: text, 10: array[string] are common configs, the rest three are special keys, 12 is for password type key for NetApp E-Series and HPE Nimble, 13 is Private Key for GCP, 14 is a config to select type of Disk for GCP
	Type_ int32 `json:"type"`
	// Takes a single value for all types except 10 and for type 14 it holds the id of the selected value from values
	Value string `json:"value,omitempty"`
	// Values to be entered. for type 10 and 14. For HPE 3PAR StoreServ, pass MA Id in name field to configure that MA as remote snap MA.
	Values []IdName `json:"values,omitempty"`
}
