/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type VmDiskFilter struct {
	// True if disk filter in vmgroup has to be overwritten, by default it will append the content
	Overwrite bool `json:"overwrite,omitempty"`
	FilterType *VmDiskFilterType `json:"filterType,omitempty"`
	// The string to be filtered
	Name string `json:"name,omitempty"`
	// The value string to be filtered, in case of disk tag , value of tag to be filtered
	Value string `json:"value,omitempty"`
	Condition *RuleOperationType `json:"condition,omitempty"`
	// VM Name of the Virtual Machine whose disk has to be filtered . This is optional. if not given, all disks of name and type from all Vms added in content will be filtered
	VmName string `json:"vmName,omitempty"`
	// VM Guid of the Virtual Machine whose disk has to be filtered . This is optional. if not given, all disks of name and type from all Vms added in content will be filtered
	VmGuid string `json:"vmGuid,omitempty"`
}
