/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type UpdateMediaAgent struct {
	// Provides the media agent with a new description.
	Description string `json:"description,omitempty"`
	Control *MediaAgentControl `json:"control,omitempty"`
	IndexCache *IndexCache `json:"indexCache,omitempty"`
	Security *UpdateSecurityAssoc `json:"security,omitempty"`
}
