/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ContentIndexingFrequencyPattern struct {
	// start date of schedule in epoch format
	StartDate int32 `json:"startDate,omitempty"`
	// Exceptions to when a schedule should not run, either in dates or week of month and day
	Exceptions []ScheduleRunException `json:"exceptions,omitempty"`
	// schedule frequency type
	ScheduleFrequencyType string `json:"scheduleFrequencyType,omitempty"`
	// Frequency of the schedule based on schedule frequency type eg. for Hours, value 2 is 2 hours, for Minutes, 30 is 30 minutes, for Daily, 2 is 2 days. for Monthly 2 is it repeats every 2 months
	Frequency int32 `json:"frequency,omitempty"`
	// Days of the week for weekly frequency
	WeeklyDays []DayOfTheWeek `json:"weeklyDays,omitempty"`
	// Day on which to run the schedule, applicable for monthly, yearly
	DayOfMonth int32 `json:"dayOfMonth,omitempty"`
	WeekOfMonth *WeekOfTheMonth `json:"weekOfMonth,omitempty"`
	DayOfWeek *DayOfWeek `json:"dayOfWeek,omitempty"`
	MonthOfYear *MonthOfYear `json:"monthOfYear,omitempty"`
	// start time of schedule in seconds for daily, weekly, monthly, yearly frequency
	StartTime int32 `json:"startTime,omitempty"`
}
