/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CreatevmGroupReq struct {
	// subclient name 
	Name string `json:"name"`
	Hypervisor *IdName `json:"Hypervisor"`
	Content *VmContent `json:"content"`
	Plan *IdName `json:"plan"`
	Storage *IdName `json:"storage,omitempty"`
	// True if Intellisnap has to be  enabled
	EnableIntellisnap bool `json:"enableIntellisnap,omitempty"`
	Meditech *MeditechPropResp `json:"Meditech,omitempty"`
}
