/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type InlineResponse20022 struct {
	// This has collection of various anomalous conditions
	AnomalousConditions []AnomalousConditionInfo `json:"anomalousConditions,omitempty"`
}
