/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Replication options for HyperV
type OverrideReplicationOptionsHyperV struct {
	// Display name for the destination VM
	VmDisplayName string `json:"vmDisplayName,omitempty"`
	// Register replicated virtual machines to the failover cluster for the destination client.
	RegisterVMWithFailoverCluster string `json:"registerVMWithFailoverCluster,omitempty"`
	// Select a network interface from the Network adapter list
	NetworkAdapter []NetworkName `json:"networkAdapter,omitempty"`
}
