/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Response body for getting subclients using particular snapEngine 
type GetSubclientForSnapEngine struct {
	SubclientDetails []SubclientDetails `json:"subclientDetails,omitempty"`
}
