/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type VirtualMachinecontent struct {
	// name of the VM to be added as content
	Name string `json:"name,omitempty"`
	// GUID of the VM to be added as content
	GUID string `json:"GUID,omitempty"`
	Type_ *VmContentType `json:"type,omitempty"`
	// Credential association ID given to link entity with credential id.
	GuestCredentialAssocId int32 `json:"guestCredentialAssocId,omitempty"`
	GuestCredentials *VmGuestCredentials `json:"guestCredentials,omitempty"`
	ExistingCredential *VmExistingCredential `json:"existingCredential,omitempty"`
}
