/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// this is the data model for return aggregate API
type GlobalEntityAggregationValueResp struct {
	Aggregation []GroupByAggregationValue `json:"aggregation,omitempty"`
}
