/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type DbRecoveryConfiguration struct {
	Server *IdName `json:"server,omitempty"`
	Instance *IdName `json:"instance,omitempty"`
	Databases []DbRecoveryConfigurationDatabase `json:"databases,omitempty"`
}
