/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type Office365SitesResp struct {
	TotalRecords int64 `json:"totalRecords,omitempty"`
	Sites []Office365SiteData `json:"sites,omitempty"`
}
