/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type SolutionTypes string

// List of SolutionTypes
const (
	GENERIC_SolutionTypes SolutionTypes = "GENERIC"
	O365_SolutionTypes SolutionTypes = "O365"
	SALESFORCE_SolutionTypes SolutionTypes = "SALESFORCE"
	EXCHANGE_SolutionTypes SolutionTypes = "EXCHANGE"
	SHAREPOINT_SolutionTypes SolutionTypes = "SHAREPOINT"
	ONEDRIVE_SolutionTypes SolutionTypes = "ONEDRIVE"
	TEAMS_SolutionTypes SolutionTypes = "TEAMS"
	DYNAMICS_365_SolutionTypes SolutionTypes = "DYNAMICS_365"
	VSA_SolutionTypes SolutionTypes = "VSA"
	FILESYSTEM_SolutionTypes SolutionTypes = "FILESYSTEM"
	KUBERNETES_SolutionTypes SolutionTypes = "KUBERNETES"
	AZURE_AD_SolutionTypes SolutionTypes = "AZURE_AD"
	CLOUD_LAPTOP_SolutionTypes SolutionTypes = "CLOUD_LAPTOP"
	FILE_STORAGE_OPTIMIZATION_SolutionTypes SolutionTypes = "FILE_STORAGE_OPTIMIZATION"
	DATA_GOVERNANCE_SolutionTypes SolutionTypes = "DATA_GOVERNANCE"
	E_DISCOVERY_SolutionTypes SolutionTypes = "E_DISCOVERY"
	SQL_SERVER_SolutionTypes SolutionTypes = "SQL_SERVER"
	ORACLEDB_SolutionTypes SolutionTypes = "ORACLEDB"
	DB2_SolutionTypes SolutionTypes = "DB2"
	ACTIVE_DIRECTORY_SolutionTypes SolutionTypes = "ACTIVE_DIRECTORY"
	DATABASE_SolutionTypes SolutionTypes = "DATABASE"
)
