/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CloudStorageDetails struct {
	General *CloudStorageGeneralInfo `json:"general,omitempty"`
	Bucket []IdNameStatus `json:"bucket,omitempty"`
	Encryption *Encryption `json:"encryption,omitempty"`
	Security []SecurityAssoc `json:"security,omitempty"`
	CacheConfigurations *CacheConfigurations `json:"cacheConfigurations,omitempty"`
	AssociatedPlans []IdName `json:"associatedPlans,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
