/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// This is the result of two objects comparision
type CompareXmlResp struct {
	// difference details in json format
	Result string `json:"result,omitempty"`
}
