/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Applicable only for credentials with Cloud Account and Vendor Type as AT&T Synaptic Storage or EMC Atmos
type CloudCredentialContentWithTokenId struct {
	// Updated name of credential
	NewName string `json:"newName,omitempty"`
	// Token ID of Credential. If updated the updated token Id is considered else the existing token Id is considered.
	TokenId string `json:"tokenId"`
	// Updated Shared secret of Credential and must be in base64 encoded format.
	SharedSecret string `json:"sharedSecret"`
	// Updated description of Credential
	Description string `json:"description,omitempty"`
	Security *UpdateCredentialSecurity `json:"security,omitempty"`
}
