/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type UserGroupSummary struct {
	// User group id
	Id int32 `json:"id,omitempty"`
	// user group name
	Name string `json:"name,omitempty"`
	// globally unique identifier for user group
	GUID string `json:"GUID,omitempty"`
	ServiceType *ServiceTypes `json:"serviceType,omitempty"`
	Description string `json:"description,omitempty"`
	Plan *IdName `json:"plan,omitempty"`
	Provider *IdName `json:"provider,omitempty"`
	// returns if the user group is enabled or disabled
	Enabled bool `json:"enabled,omitempty"`
	// This property denotes that addition of users/groups from child companies is allowed. Only applicable for commcell and reseller company group.
	AllowMultipleCompanyMembers bool `json:"allowMultipleCompanyMembers,omitempty"`
	Company *IdName `json:"company,omitempty"`
	Commcell *CommcellInfo `json:"commcell,omitempty"`
	Users []IdName `json:"users,omitempty"`
	GlobalConfigInfo *GlobalConfigInfo `json:"globalConfigInfo,omitempty"`
}
