/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// AccessType : The access type for the access path can be either read (writing to path not allowed) or read and write (writing to path allowed).
type AccessType string

// List of AccessType
const (
	READ_AND_WRITE_AccessType AccessType = "READ_AND_WRITE"
	READ_AccessType AccessType = "READ"
)
