/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type DatabaseListResp struct {
	// List of databases
	Databases []DatabaseSummary `json:"databases,omitempty"`
}
