/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// ActionType : Enum for Action Type
type ActionType string

// List of ActionType
const (
	NONE_ActionType ActionType = "NONE"
	REGULAR_ActionType ActionType = "REGULAR"
	RECALL_ActionType ActionType = "RECALL"
)
