/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type VmHypervisorSecurityProp struct {
	// Client owners for the Hypervisor
	ClientOwners string `json:"clientOwners,omitempty"`
	AssociatedUserGroups []IdName `json:"associatedUserGroups,omitempty"`
}
