/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type InventoryAssetList struct {
	Assets []InventoryAssetSummary `json:"assets,omitempty"`
}
