/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// List of plans associated to the region
type AssociatedRegionBasedPlansList struct {
	Plan *IdName `json:"plan,omitempty"`
	AssociatedServers int32 `json:"associatedServers,omitempty"`
	Type_ *PlanType `json:"type,omitempty"`
}
