/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Provider attributes for LDAP app
type LdapAttributes struct {
	// Custom attribute string of LDAP query paramters
	UserGroupFilter string `json:"userGroupFilter,omitempty"`
	// Custom attribute string of LDAP query paramters
	UserFilter string `json:"userFilter,omitempty"`
	// Custom attribute string of LDAP query paramters
	UniqueIdentifier string `json:"uniqueIdentifier,omitempty"`
	// Custom attribute string of LDAP query paramters
	BaseDN string `json:"baseDN,omitempty"`
}
