/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type EntityAuditList struct {
	// List of audit information for an entity
	AuditDetails []EntityAuditInformation `json:"auditDetails,omitempty"`
}
