/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type Office365MailboxesReq struct {
	Office365Plan *IdName `json:"office365Plan"`
	Mailboxes []Office365MailboxesReqEntity `json:"mailboxes"`
}
