/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// ArchFileType : Job Archive File type
type ArchFileType string

// List of ArchFileType
const (
	DATA_ArchFileType ArchFileType = "DATA"
	INDEX_ArchFileType ArchFileType = "INDEX"
	ARCHIVE_FILE_ArchFileType ArchFileType = "ARCHIVE_FILE"
	LOG_ArchFileType ArchFileType = "LOG"
	JOB_METADATA_ArchFileType ArchFileType = "JOB_METADATA"
	NA_ArchFileType ArchFileType = "NA"
)
