/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Network interface for the destination instances
type AzureNetwork struct {
	// Network unique identifier
	NetworkId string `json:"networkId,omitempty"`
	// Display Name of network
	NetworkDisplayName string `json:"networkDisplayName,omitempty"`
	// subnet id of network
	SubnetId string `json:"subnetId,omitempty"`
	// Name of the network
	NetworkName string `json:"networkName,omitempty"`
	NetworkAddressDetails *AzureDestinationInfoNic `json:"networkAddressDetails,omitempty"`
	// Private IP address of the network
	PrivateIPaddress string `json:"privateIPaddress,omitempty"`
	// Public IP address of the network
	PublicIPAddress string `json:"publicIPAddress,omitempty"`
	// Azure public IP address ID. Format: /subscriptions/{Subscription ID}/resourceGroups/{Resource Group Name}/providers/Microsoft.Network/publicIPAddresses/{Public IP Address Name}.
	PublicIPaddressID string `json:"publicIPaddressID,omitempty"`
}
