/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type GetApplicationGroupDetails struct {
	ApplicationCount *KubernetesApplicationCountInfo `json:"applicationCount,omitempty"`
	Cluster *IdNameDisplayName `json:"cluster,omitempty"`
	Instance *IdName `json:"instance,omitempty"`
	Backupset *IdName `json:"backupset,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
