/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type PlanSummary struct {
	Plan *IdName `json:"plan,omitempty"`
	PlanType *PlanType `json:"planType,omitempty"`
	ParentPlan *IdName `json:"parentPlan,omitempty"`
	// This tells the content indexing target apps for data classification plans
	TargetApp []PlanTargetApp `json:"targetApp,omitempty"`
	// Count of associated entities for the plan
	AssociatedEntities int32 `json:"associatedEntities,omitempty"`
	// RPO in minutes for the plan
	RPO int32 `json:"RPO,omitempty"`
	// Number of copies for the plan
	NumberOfCopies int32 `json:"numberOfCopies,omitempty"`
	Status *PlanStatus `json:"status,omitempty"`
	// For plans in incomplete state contains list of entities missing from the plan
	MissingEntities []IdName `json:"missingEntities,omitempty"`
	// This lists the various resource Pools of different app types associated with storage pools of plan
	ResourcePool []IdName `json:"resourcePool,omitempty"`
	// Tags associated with this plan
	Tags []IdNameValue `json:"tags,omitempty"`
	Company *IdName `json:"company,omitempty"`
	// Tells which commcell this plan belongs to.
	Commcell string `json:"commcell,omitempty"`
	// Tells if this plan can be used to derive from and create a new child plan
	Derivable bool `json:"derivable,omitempty"`
	GlobalConfigInfo *GlobalConfigInfo `json:"globalConfigInfo,omitempty"`
}
