/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type IdNameDisplayNameCompany struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Company *IdName `json:"company,omitempty"`
}
