/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type VmSecurity struct {
	Associations []VmSecurityAssoc `json:"associations,omitempty"`
	Permissions []PermissionResp `json:"permissions,omitempty"`
	Owners []SecurityOwnersAssoc `json:"owners,omitempty"`
}
