/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type AlertCriteriaIdNameValue struct {
	Value string `json:"value,omitempty"`
	// id of the criteria of detection for the alert definition
	Id int32 `json:"id,omitempty"`
	// criteria of detection for the alert definition
	Name string `json:"name,omitempty"`
	ParamsList []AlertDefinitionsCriteriaParams `json:"paramsList,omitempty"`
	NotificationCriteria *NotificationCriteriaOptions `json:"notificationCriteria,omitempty"`
}
