/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type InlineResponse2005 struct {
	HyperScaleStorage []StorageListSummary `json:"hyperScaleStorage,omitempty"`
}
