/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type FirewallTopologyDetails struct {
	Topology *IdName `json:"topology,omitempty"`
	TopologyType *FirewallTopologyTypes `json:"topologyType,omitempty"`
	ClientType *FirewallClientType `json:"clientType,omitempty"`
	// Flag determining wether network gateways are used to connect all infrastructure machines
	UseWildCardProxy bool `json:"useWildCardProxy,omitempty"`
	FirewallGroups []FirewallTopologyGroups `json:"firewallGroups,omitempty"`
	// Flag determining if we want the data from tunnel to use HTTPS protocol
	EncryptTraffic bool `json:"encryptTraffic,omitempty"`
	TunnelProtocol *FirewallTopologyTunnelProtocol `json:"tunnelProtocol,omitempty"`
	// The number of tunnel connections per route
	TunnelsPerRoute int32 `json:"tunnelsPerRoute,omitempty"`
}
