/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Info for the Windows/Unix ISO files
type IsoInfo struct {
	// Path for the Windows/Unix ISO files
	IsoPath string `json:"isoPath,omitempty"`
	// OS Type name
	OsType string `json:"osType,omitempty"`
}
