/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Details of Slot
type SlotInfo struct {
	Slot *IdName `json:"slot,omitempty"`
	SlotType *SlotTypes `json:"slotType,omitempty"`
	// Id of Library
	LibraryId int32 `json:"libraryId,omitempty"`
	// Id of Media
	MediaId int32 `json:"mediaId,omitempty"`
	MediaDetails *MediaDetails `json:"mediaDetails,omitempty"`
}
