/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type LaptopPlanStorageAndSchedule struct {
	PrimaryStorage *IdName `json:"primaryStorage"`
	SecondaryStorage *IdName `json:"secondaryStorage,omitempty"`
	// Recovery Point Objective (RPO) is the maximum amount of time that data can be lost during a service disruption. Your RPO determines the frequency of your backup jobs. Your RPO is met through automatic options. The time specified in minutes here is your RPO if none of the automatic options are met. Default is 480 minutes (8 hours).
	BackupFrequency int32 `json:"backupFrequency,omitempty"`
}
