/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// StorageUpdateType : Enum which specifies the type of storage update
type StorageUpdateType string

// List of StorageUpdateType
const (
	DISRUPTIVE_StorageUpdateType StorageUpdateType = "DISRUPTIVE"
	NON_DISRUPTIVE_StorageUpdateType StorageUpdateType = "NON_DISRUPTIVE"
)
