/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// AWS security group info for restore
type VmSecurityGroupInfo struct {
	GroupId string `json:"groupId,omitempty"`
	GroupName string `json:"groupName,omitempty"`
}
