/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type AmazonS3Bucket struct {
	// Name of cloud vendor
	CloudType string `json:"cloudType"`
	MediaAgent *IdName `json:"mediaAgent"`
	// IP address or fully qualified domain name or URL for the cloud library based on cloud vendor
	ServiceHost string `json:"serviceHost"`
	// Authentication type for the cloud storage server
	Authentication string `json:"authentication"`
	// Needed for AWS STS assume role and AWS STS assume role with IAM role policy
	ArnRole string `json:"arnRole,omitempty"`
	Credentials *IdName `json:"credentials,omitempty"`
	// Name of bucket
	Bucket string `json:"bucket"`
	// Appropriate storage class for your account
	StorageClass string `json:"storageClass"`
	// If the MediaAgent accesses the mount path using a proxy then proxy server address needs to be provided. If you want to remove proxy information, pass empty string in proxyAddress.
	ProxyAddress string `json:"proxyAddress,omitempty"`
	// Port for proxy configuration
	Port int32 `json:"port,omitempty"`
	// Username for proxy configuration
	Username string `json:"username,omitempty"`
	// Password for proxy configuration (Should be in Base64 format)
	Password string `json:"password,omitempty"`
}
