/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type RmConfigureRequest struct {
	// List of project ids
	ProjectIds []int32 `json:"projectIds"`
	// List of reviewers for the request
	Reviewers []IdNameDisplayName `json:"reviewers"`
	// List of approvers for the request
	Approvers []IdNameDisplayName `json:"approvers,omitempty"`
}
