/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type DriveSummary struct {
	// drive type.
	Type_ string `json:"type,omitempty"`
	// status of a drive.
	Online string `json:"online,omitempty"`
	// access of a drive.
	Status string `json:"status,omitempty"`
	// barCode of a drive.
	BarCode string `json:"barCode,omitempty"`
	// mountStatus of a drive.
	MountStatus string `json:"mountStatus,omitempty"`
	// media Agent of the drive.
	ActiveMediaAgent string `json:"activeMediaAgent,omitempty"`
	// if  the drive attribute is 1 then the drive is cleanable.
	DriveAttributes int32 `json:"driveAttributes,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
