/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type Office365ExchRestoreCommonOptions struct {
	IfMessageExists string `json:"ifMessageExists,omitempty"`
	// Include deleted items on Restore
	DeletedItems bool `json:"deletedItems,omitempty"`
	// Match destination user based on the email address
	MatchEmailAddress bool `json:"matchEmailAddress,omitempty"`
}
