/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// These are users and groups who will be allowed to manage the company. Different roles can be assigned for each tenant operator for the company. Either id/name of the user/usergroup/roles can be provided. If both id and name are provided, id will be taken into consideration.
type TenantOperator struct {
	User *IdName `json:"user,omitempty"`
	UserGroup *IdName `json:"userGroup,omitempty"`
	Role *IdName `json:"role,omitempty"`
}
