/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Retire servers response
type RetireServersResponse struct {
	JobId int64 `json:"jobId,omitempty"`
	Error_ *GenericRespWithWarning `json:"error,omitempty"`
}
