/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type PsaType string

// List of PSAType
const (
	CONNECTWISE_PsaType PsaType = "CONNECTWISE"
	AUTOTASK_PsaType PsaType = "AUTOTASK"
)
