/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CreateCdmPlan struct {
	// Name of the new plan
	PlanName string `json:"planName"`
	// Copy destinations for the plan. Specify where you want to store your data.
	BackupDestinations []CreatePlanBackupDestination `json:"backupDestinations"`
	Rpo *ServerBackupPlanRpo `json:"rpo,omitempty"`
	SnapshotOptions *CreatePlanSnapshotOptions `json:"snapshotOptions,omitempty"`
	DatabaseOptions *ServerPlanDatabaseOptions `json:"databaseOptions,omitempty"`
}
