/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type MediaAgentForDdbListResponse struct {
	MediaAgents []MediaAgentForDdbSummary `json:"mediaAgents,omitempty"`
}
