/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Modify failover group request
type ModifyFailoverGroupRequest struct {
	// Failover Group name
	Name string `json:"name,omitempty"`
	// Whether a user approval is required for DR operations
	IsApprovalRequired bool `json:"isApprovalRequired,omitempty"`
	// Users to notify/for approval of DR operations
	UsersToNotify []IdNameDisplayNameCompany `json:"usersToNotify,omitempty"`
	// The interval between DR operations of different priorities
	PriorityIntervalInMinutes int32 `json:"priorityIntervalInMinutes,omitempty"`
	// The list of all ESX server mappings
	EsxServerMappings []EsxServerMapping `json:"esxServerMappings,omitempty"`
	// Whether to continue to next priority on DR job failure
	ContinueDROnFailure bool `json:"continueDROnFailure,omitempty"`
	RecoveryTarget *IdName `json:"recoveryTarget,omitempty"`
	// List of all replication pairs that are part of the failover group
	ReplicationPairs []FailoverGroupReplicationPair `json:"replicationPairs,omitempty"`
	// List of all array replication pairs for failover group
	ArrayReplicationPairs []FailoverGroupArrayReplicationPair `json:"arrayReplicationPairs,omitempty"`
	Script *ReplicationGroupScript `json:"script,omitempty"`
}
