/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type HypervisorPropertiesResp struct {
	Id int32 `json:"id,omitempty"`
	// Hypervisor Name
	Name string `json:"name,omitempty"`
	// Display Name
	DisplayName string `json:"displayName,omitempty"`
	Instance *IdName `json:"instance,omitempty"`
	General *HypervisorGeneralProperties `json:"general,omitempty"`
	AccountDetails *HypervisorAccountDetails `json:"accountDetails,omitempty"`
	ActivityControl *ActivityControlOptions `json:"activityControl,omitempty"`
	Settings *HypervisorSettings `json:"settings,omitempty"`
	AccessNodeList *AccessNodeListModel `json:"accessNodeList,omitempty"`
	HypervisorCommonProperties *HypervisorCommonProps `json:"hypervisorCommonProperties,omitempty"`
	ManageSnapshot *IdName `json:"manageSnapshot,omitempty"`
}
