/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Application details for mount request.
type VsaApplicationDetails struct {
	// subclient id associated to snapshot
	SubclientId int32 `json:"subclientId,omitempty"`
	// hypervisor Id of hypervisor where user is mounting snapshot
	ClientId int32 `json:"clientId,omitempty"`
	// instance id of the instance to which subclient is associated
	InstanceId int32 `json:"instanceId,omitempty"`
	// apptype id or agent type
	ApptypeId int32 `json:"apptypeId,omitempty"`
}
