/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// FirewallGroupMnemonic : Custom names(mnemonics) given to pre-defined smart client groups
type FirewallGroupMnemonic string

// List of FirewallGroupMnemonic
const (
	MY_COMMSERVE_FirewallGroupMnemonic FirewallGroupMnemonic = "MY_COMMSERVE"
	MY_MEDIAAGENTS_FirewallGroupMnemonic FirewallGroupMnemonic = "MY_MEDIAAGENTS"
	MY_COMMSERVE_AND_MEDIAAGENTS_FirewallGroupMnemonic FirewallGroupMnemonic = "MY_COMMSERVE_AND_MEDIAAGENTS"
	NONE_FirewallGroupMnemonic FirewallGroupMnemonic = "NONE"
)
