/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type AlertDefinitionsCreateAlertType struct {
	// Defines the category of the alert
	Category string `json:"category,omitempty"`
	// Defines the criteria of the alert
	Criteria string `json:"criteria,omitempty"`
	ParamsList []AlertDefinitionsCriteriaParams `json:"paramsList,omitempty"`
	NotificationCriteria *NotificationCriteriaOptions `json:"notificationCriteria,omitempty"`
}
