/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// select one of below option for filtering
type TaskEntity struct {
	SubclientId int32 `json:"subclientId,omitempty"`
	StoragePolicyId int32 `json:"storagePolicyId,omitempty"`
	CopyId int32 `json:"copyId,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	ClientGroupId int32 `json:"clientGroupId,omitempty"`
	ApplicationId int32 `json:"applicationId,omitempty"`
	LibraryId int32 `json:"libraryId,omitempty"`
	BackupsetId int32 `json:"backupsetId,omitempty"`
	InstanceId int32 `json:"instanceId,omitempty"`
	WorkflowId int32 `json:"workflowId,omitempty"`
	TrackingPolicyId int32 `json:"trackingPolicyId,omitempty"`
}
