/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// parentEntity1 can start from SERVER_ENTITY or SERVER_GROUP_ENTITY and subsequentily ending up at parentEntity4 or parentEntity5 with Backupset.
type SubclientAssocParentEntity struct {
	// id of the associated entity
	Id int32 `json:"id,omitempty"`
	// name of the associated entity
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
}
