/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Entity applicable for plan association via plan assignment rules.
type PlanRuleApplicableEntity struct {
	Subclient *IdName `json:"subclient,omitempty"`
	Backupset *IdName `json:"backupset,omitempty"`
	Instance *IdName `json:"instance,omitempty"`
	Client *IdName `json:"client,omitempty"`
	Apptype *IdName `json:"apptype,omitempty"`
	EvaluatedPlan *IdName `json:"evaluatedPlan,omitempty"`
	CurrentPlan *IdName `json:"currentPlan,omitempty"`
	RuleDetails *PlanEntityRuleInfo `json:"ruleDetails,omitempty"`
}
