/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CreateApplicationGroupRequest struct {
	Cluster *IdName `json:"cluster"`
	// Specify new name to rename an Application Group
	Name string `json:"name"`
	Plan *IdName `json:"plan,omitempty"`
	Content *KubernetesApplicationGroupContent `json:"content"`
	Filters *KubernetesApplicationGroupFilters `json:"filters,omitempty"`
}
