/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of entities that are will be associated to provided plan and said rule
type AssociatePlanRuleEntityList struct {
	// Details of entity that will be associated to plan and rule.
	Entities []AssociatePlanRuleEntity `json:"entities,omitempty"`
}
