/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// These rules are enforced only when archiving is set to true
type ArchivingRules struct {
	// When free disk space falls below specified amount (in percentage), start cleaning up the disk
	StartCleaningIfLessThan int32 `json:"startCleaningIfLessThan,omitempty"`
	// When free disk space more than specified amount (in percentage), stop cleaning up the disk
	StopCleaningIfupto int32 `json:"stopCleaningIfupto,omitempty"`
	// To archive files based on the last accessed date of each file within the folder, specify the number of days
	FileAccessTimeOlderThan int32 `json:"fileAccessTimeOlderThan,omitempty"`
	// To archive files based on the last modified date of each file within the folder, specify the number of days
	FileModifiedTimeOlderThan int32 `json:"fileModifiedTimeOlderThan,omitempty"`
	// To archive files based on the time the files were created within the folder, specify the number of days
	FileCreatedTimeOlderThan int32 `json:"fileCreatedTimeOlderThan,omitempty"`
	// To archive files based on the size of the file, specify the minimum file size in KB. All files whose size ranges between the minimum and maximum values are archived.
	FileSizeGreaterThan int32 `json:"fileSizeGreaterThan,omitempty"`
	// To archive files based on the size of the file, specify the maximum file size in KB. All files whose size ranges between the minimum and maximum values are archived.
	MaximumFileSize int32 `json:"maximumFileSize,omitempty"`
	// To archive files based on the Read-Only attribute, set to TRUE
	ArchiveReadOnlyFiles bool `json:"archiveReadOnlyFiles,omitempty"`
	AfterArchiving *ArchivingRulesFile `json:"afterArchiving,omitempty"`
}
