/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Specific options to be set on schedules
type ScheduleOption struct {
	// Used to enable disk caching feature on databases for automatic schedules on server plan
	UseDiskCacheForLogBackups bool `json:"useDiskCacheForLogBackups,omitempty"`
	// Commit frequency in hours for disk cache backups from automatic schedules
	CommitFrequencyInHours int32 `json:"commitFrequencyInHours,omitempty"`
	// Number of days between auto conversion of backup level applicable for databases on incremental and differential schedules of server plan
	DaysBetweenAutoConvert int32 `json:"daysBetweenAutoConvert,omitempty"`
	// item backup option for O365 V2 backup jobs
	O365ItemSelectionOption string `json:"o365ItemSelectionOption,omitempty"`
	// total job running time in minutes
	JobRunningTimeInMins int32 `json:"jobRunningTimeInMins,omitempty"`
	// The min number of mins to check for file activity on automatic schedule.
	MinBackupIntervalInMins int32 `json:"minBackupIntervalInMins,omitempty"`
	// The min number of archived log files before a backup job should start
	LogFilesThreshold int32 `json:"logFilesThreshold,omitempty"`
	// The min log destination disk threshold percentage
	LogsDiskUtilizationPercent int32 `json:"logsDiskUtilizationPercent,omitempty"`
}
