/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CreateGlobalServerPlan struct {
	Plan *CreateServerPlan `json:"plan,omitempty"`
	GlobalConfigInfo *CreateGlobalConfigInfo `json:"globalConfigInfo,omitempty"`
}
