/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type DellEmcBucketContentResp struct {
	// Name of cloud vendor
	CloudType string `json:"cloudType,omitempty"`
	MediaAgent *IdName `json:"mediaAgent,omitempty"`
	// IP address or fully qualified domain name or URL for the cloud library based on cloud vendor
	ServiceHost string `json:"serviceHost,omitempty"`
	Credentials *IdName `json:"credentials,omitempty"`
	// Name of bucket
	Bucket string `json:"bucket,omitempty"`
	// If the MediaAgent accesses the mount path using a proxy then proxy server address needs to be provided. If you want to remove proxy information, pass empty string in proxyAddress.
	ProxyAddress string `json:"proxyAddress,omitempty"`
	// Port for proxy configuration
	Port int32 `json:"port,omitempty"`
	// Username for proxy configuration
	Username string `json:"username,omitempty"`
	// Password for proxy configuration (Should be in Base64 format)
	Password string `json:"password,omitempty"`
	Access *AccessType `json:"access,omitempty"`
	// Enable/Disable access of bucket to a media Agent
	Enable bool `json:"enable,omitempty"`
	// Id of the bucket
	Id int32 `json:"id,omitempty"`
	// MediaAgent display name along with name of the bucket
	Name string `json:"name,omitempty"`
	Configuration *CloudBucketConfiguration `json:"configuration,omitempty"`
	CloudAccessPaths []CloudAccessPathsResp `json:"cloudAccessPaths,omitempty"`
}
