/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CreateServerPlanRpo struct {
	Rpo *ServerBackupPlanRpo `json:"rpo"`
	DatabaseOptions *ServerPlanDatabaseOptions `json:"databaseOptions,omitempty"`
}
