/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Model for update create recovery group
type CreateRecoveryGroupResp struct {
	RecoveryGroup *IdName `json:"recoveryGroup,omitempty"`
	Error_ *GenericResp `json:"error,omitempty"`
}
