/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type AzureAdAppToken struct {
	// User based refresh token generated with corresponding app credentials. Can be left blank if the azure app is protected API approved.
	RefreshToken string `json:"refreshToken,omitempty"`
	// Azure Application ID
	ApplicationId string `json:"applicationId"`
	// Azure app secret key, needs to be base64 encoded
	ApplicationSecret string `json:"applicationSecret"`
	// Password of the azure application certificate and must be in base64 encoded format. Only applicable for SharePoint Online
	CertificatePassword string `json:"certificatePassword,omitempty"`
	// Content of the azure application certificate file and must be in base64 encoded format. Accepted fileTypes are pfx, p12. Only applicable for SharePoint Online
	Certificate string `json:"certificate,omitempty"`
	// Thumbprint of the azure application certificate file. Only applicable for SharePoint Online
	CertificateThumbprint string `json:"certificateThumbprint,omitempty"`
}
