/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// RecoveryStatus : Status of recovery entity
type RecoveryStatus string

// List of RecoveryStatus
const (
	NO_STATUS_RecoveryStatus RecoveryStatus = "NO_STATUS"
	NOT_READY_RecoveryStatus RecoveryStatus = "NOT_READY"
	READY_RecoveryStatus RecoveryStatus = "READY"
	RECOVERED_RecoveryStatus RecoveryStatus = "RECOVERED"
	FAILED_RecoveryStatus RecoveryStatus = "FAILED"
	RECOVERED_WITH_ERRORS_RecoveryStatus RecoveryStatus = "RECOVERED_WITH_ERRORS"
	IN_PROGRESS_RecoveryStatus RecoveryStatus = "IN_PROGRESS"
	CLEANED_UP_RecoveryStatus RecoveryStatus = "CLEANED_UP"
	MARK_AS_FAILED_RecoveryStatus RecoveryStatus = "MARK_AS_FAILED"
	CLEANUP_FAILED_RecoveryStatus RecoveryStatus = "CLEANUP_FAILED"
)
