/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type DcPlanCiFileFilters struct {
	IncludeDocTypes string `json:"includeDocTypes,omitempty"`
	ExcludePaths []string `json:"excludePaths,omitempty"`
	MinDocSize int32 `json:"minDocSize,omitempty"`
	MaxDocSize int32 `json:"maxDocSize,omitempty"`
}
