/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type CommCellNameHostName struct {
	// CommServer name
	Name string `json:"name,omitempty"`
	// CommServer host name
	HostName string `json:"hostName,omitempty"`
}
