/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type ServiceCommcellInfo struct {
	Commcell *IdNameGuid `json:"Commcell,omitempty"`
	// Version of the service commcell.
	Version string `json:"Version,omitempty"`
	// Returns active management status of the service commcell.
	ActiveManagementStatus string `json:"activeManagementStatus,omitempty"`
}
