/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type BackupOperationsList struct {
	// Full job is selected or not for blackout window
	Full bool `json:"full,omitempty"`
	// Synthetic Full job is selected or not for blackout window
	SyntheticFull bool `json:"syntheticFull,omitempty"`
	// Transaction Log job is selected or not for blackout window
	TransactionLog bool `json:"transactionLog,omitempty"`
	// Incremental and Differential job is selected or not for blackout window
	IncrementalAndDifferential bool `json:"incrementalAndDifferential,omitempty"`
}
