/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

// Model to provide basic detail of recovery group
type RecoveryGroup struct {
	// Id of the recovery group
	Id int32 `json:"id,omitempty"`
	// Name of the recovery group
	Name string `json:"name,omitempty"`
	Target *IdName `json:"target,omitempty"`
	PostRecoveryActions []DrOperationScript `json:"postRecoveryActions,omitempty"`
	// The delay between machines in different priorities in minutes
	DelayBetweenPriorityMachines int32 `json:"delayBetweenPriorityMachines,omitempty"`
	// Set to true to continue to the next priority machines on failure
	ContinueOnFailure bool `json:"continueOnFailure,omitempty"`
	Action *RecoveryAction `json:"action,omitempty"`
	RecoveryPointDetails *RecoveryGroupRpDetails `json:"recoveryPointDetails,omitempty"`
	// Timestamp for group restore in case of disaster
	RecoveryPoint int32 `json:"recoveryPoint,omitempty"`
	RecoveryExpirationOptions *RecoveryExpirationOptions `json:"recoveryExpirationOptions,omitempty"`
}
