/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer

type UpdateHypervisorGroupAzureStack struct {
	HypervisorType string `json:"hypervisorType"`
	// Tenant id of Azure Stack login Application
	TenantId string `json:"tenantId,omitempty"`
	// Client Name to Update
	ServerName string `json:"serverName,omitempty"`
	// subscription id of Azure Stack
	SubscriptionId string `json:"subscriptionId,omitempty"`
	// Application id of Azure login Application
	ApplicationId string `json:"ApplicationId,omitempty"`
	// Application Password of Azure login Application
	ApplicationPassword string `json:"ApplicationPassword,omitempty"`
	// Resource manager URL for Azure Stack client
	ResourceManagerURL string `json:"resourceManagerURL,omitempty"`
	// Use managed identities for Azure stack authentication
	UseManagedIdentity bool `json:"useManagedIdentity,omitempty"`
	AccessNodes []AccessNodeModel `json:"accessNodes,omitempty"`
	FbrUnixMediaAgent *IdName `json:"fbrUnixMediaAgent,omitempty"`
	ActivityControl *ActivityControlOptions `json:"activityControl,omitempty"`
	Security *VmHypervisorSecurityProp `json:"security,omitempty"`
	// The name of the hypervisor that has to be changed
	NewName string `json:"newName,omitempty"`
	Settings *HypervisorSettings `json:"settings,omitempty"`
	Credentials *IdName `json:"credentials,omitempty"`
	// if credential validation has to be skipped.
	SkipCredentialValidation bool `json:"skipCredentialValidation,omitempty"`
}
