/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiexplorer
// EncryptionTypes : The different types of encryption keys that can be used for encrypting the data. The values are case sensitive
type EncryptionTypes string

// List of EncryptionTypes
const (
	BLOW_FISH_EncryptionTypes EncryptionTypes = "BlowFish"
	AES_EncryptionTypes EncryptionTypes = "AES"
	DES3_EncryptionTypes EncryptionTypes = "DES3"
	GOST_EncryptionTypes EncryptionTypes = "GOST"
	SERPENT_EncryptionTypes EncryptionTypes = "Serpent"
	TWOFISH_EncryptionTypes EncryptionTypes = "Twofish"
)
