/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type TokenRuleGroup struct {
	Match *TokenRuleGroupOperation `json:"match,omitempty"`
	// List of rules
	Rules []TokenRule `json:"rules,omitempty"`
}
