/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// For newly added location - country, latitude and longitude are mandatory fields. Any existing location added to locations array needs to have all the existing fields. 
type UpdateRegion struct {
	// New name for the region
	NewName string `json:"newName,omitempty"`
	// Type of operation to be performed for locations
	LocationsOperationType string `json:"locationsOperationType,omitempty"`
	Locations []LocationDetailsWithZone `json:"locations,omitempty"`
}
