/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type TcoCalculateResponse struct {
	Commvault *TcoCostParameters `json:"commvault,omitempty"`
	Native *TcoCostParameters `json:"native,omitempty"`
}
