/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Array config template for editArrayDetails
type ArrayConfigsEdit struct {
	// This is the masterConfigId, which is available for each vendor's configs
	MasterConfigId int32 `json:"masterConfigId"`
	// This is the name of the config which is displayed on the Command Center Console
	Name string `json:"name"`
	// Type of the config value. type can accept 7 values [1,2,8,10,12,13,14], 1: boolean, 2: integer, 8: text, 10: array[string] are common configs, the rest three are special keys, 12 is for password type key for NetApp E-Series and HPE Nimble, 13 is Private Key for GCP, 14 is a hidden config to select type of Disk for GCP
	Type_ int32 `json:"type"`
	// Takes a single value for all types and for type 14 it holds the id of the selected value from values
	Value string `json:"value,omitempty"`
	// For type 10 and 14, it can take one or more value of idname type where id by default is 0 for 10. For HPE 3PAR StoreServ, pass MA Id in name field to configure that MA as remote snap MA.
	Values []IdName `json:"values,omitempty"`
	// Flag regarding placement of config in the CC page
	Flags int32 `json:"flags"`
	// Whether the config is updated/edited or not
	IsUpdated bool `json:"isUpdated"`
}
