/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type PlanBackupDestinations struct {
	Backupdestinations []PlanBackupDestination `json:"backupdestinations,omitempty"`
	// Specifies if the plan has region-based storage
	RegionsConfigured bool `json:"regionsConfigured,omitempty"`
}
