/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// An object containing smVolumeId of snaps and commcell id of the setup
type SnapVolumes struct {
	// smVolumeId of the snap
	SmVolumeId int32 `json:"smVolumeId"`
	// Commcell Id of the setup
	CommCellId int32 `json:"commCellId,omitempty"`
}
