/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type BackupOperations string

// List of BackupOperations
const (
	FULL_BackupOperations BackupOperations = "FULL"
	INCREMENTAL_AND_DIFFERENTIAL_BackupOperations BackupOperations = "INCREMENTAL_AND_DIFFERENTIAL"
	SYNTHETIC_FULL_BackupOperations BackupOperations = "SYNTHETIC_FULL"
	TRANSACTION_LOG_BackupOperations BackupOperations = "TRANSACTION_LOG"
	ALL_OPERATIONS_BackupOperations BackupOperations = "ALL_OPERATIONS"
	DATA_RECOVERY_BackupOperations BackupOperations = "DATA_RECOVERY"
	AUXILIARY_COPY_BackupOperations BackupOperations = "AUXILIARY_COPY"
	DISASTER_RECOVERY_BACKUP_BackupOperations BackupOperations = "DISASTER_RECOVERY_BACKUP"
	DATA_VERIFICATION_BackupOperations BackupOperations = "DATA_VERIFICATION"
	ERASE_SPARE_MEDIA_BackupOperations BackupOperations = "ERASE_SPARE_MEDIA"
	SHELF_MANAGEMENT_BackupOperations BackupOperations = "SHELF_MANAGEMENT"
	DELETE_DATA_BY_BROWSING_BackupOperations BackupOperations = "DELETE_DATA_BY_BROWSING"
	DELETE_ARCHIVED_DATA_BackupOperations BackupOperations = "DELETE_ARCHIVED_DATA"
	OFFLINE_CONTENT_INDEXING_BackupOperations BackupOperations = "OFFLINE_CONTENT_INDEXING"
	ONLINE_CONTENT_INDEXING_BackupOperations BackupOperations = "ONLINE_CONTENT_INDEXING"
	INFORMATION_MANAGEMENT_BackupOperations BackupOperations = "INFORMATION_MANAGEMENT"
	MEDIA_REFRESHING_BackupOperations BackupOperations = "MEDIA_REFRESHING"
	DATA_ANALYTICS_BackupOperations BackupOperations = "DATA_ANALYTICS"
	DATA_PRUNING_BackupOperations BackupOperations = "DATA_PRUNING"
	BACKUP_COPY_BackupOperations BackupOperations = "BACKUP_COPY"
	STUBBING_BackupOperations BackupOperations = "STUBBING"
	INSTALL_UPDATES_BackupOperations BackupOperations = "INSTALL_UPDATES"
)
