/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type GetHypervisorFilterResp struct {
	Filters []VmContent `json:"filters,omitempty"`
	DiskFilters []VmDiskFilterProp `json:"diskFilters,omitempty"`
}
