/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Request body for download or copy software
type DownloadOrCopySoftware struct {
	DownloadConfiguration *DownloadConfiguration `json:"downloadConfiguration,omitempty"`
	CopyConfiguration *CopyConfiguration `json:"copyConfiguration,omitempty"`
	// Boolean which determines whether to notify when software is downloaded or copied.
	NotifyWhenJobCompletes bool `json:"notifyWhenJobCompletes,omitempty"`
}
