/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CloudStorageProxy struct {
	// If the MediaAgent accesses the mount path using a proxy then proxy server address needs to be provided. If you want to remove proxy information, pass empty string in proxyAddress.
	ProxyAddress string `json:"proxyAddress,omitempty"`
	// Port for proxy configuration
	Port int32 `json:"port,omitempty"`
	// Username for proxy configuration
	Username string `json:"username,omitempty"`
	// Password for proxy configuration (Should be in Base64 format)
	Password string `json:"password,omitempty"`
}
