/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// To display the list of Inventory response of Resource Pool
type ResourcePoolInventoryResponseList struct {
	HostInfo []ResourcePoolInventoryResponse `json:"hostInfo,omitempty"`
}
