/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type VendorResp struct {
	SnapVendor *IdName `json:"snapVendor,omitempty"`
	Capabilities *VendorCapabilities `json:"capabilities,omitempty"`
	CloudVendorId int32 `json:"cloudVendorId,omitempty"`
	Label *ArrayLabel `json:"label,omitempty"`
}
