/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Refers to default data protection plans to use for the company. There can be a default plan for each subtype.
type DefaultPlan struct {
	Subtype *SubTypes `json:"subtype,omitempty"`
	// Id of the default plan. Either id or name can be provided. If both id and name are provided, id is given first preference.
	Id int32 `json:"id,omitempty"`
	// Name of the default plan. Either id or name can be provided. If both id and name are provided, id is given first preference.
	Name string `json:"name,omitempty"`
}
