/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Request Message for sharepoint app creation
type CreateSharepointClient struct {
	// Unique Sharepoint app name
	Name string `json:"name"`
	ServerPlan *IdName `json:"serverPlan"`
	// SharePoint Online tenant admin site URL
	TenantAdminSiteURL string `json:"tenantAdminSiteURL"`
	AzureApp *Office365ConnectionsSettings `json:"azureApp"`
}
