/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// This feature applies only to File System Agents
type PlanSnapshotOptions struct {
	// Flag to enable backup copy
	EnableBackupCopy bool `json:"enableBackupCopy,omitempty"`
	// Backup copy RPO in minutes
	BackupCopyRPOMins int32 `json:"backupCopyRPOMins,omitempty"`
	BackupCopyFrequency *BackupFrequencyPattern `json:"backupCopyFrequency,omitempty"`
	// Flag to enable deferred snapshot cataloging
	EnableSnapCatalog bool `json:"enableSnapCatalog,omitempty"`
	BackupCopyOptions *BackupCopyOptions `json:"backupCopyOptions,omitempty"`
	// Error message to indicate the cause of sync issue (if any) between CommServ DB and Command center with respect to snapshot options.
	SyncError string `json:"syncError,omitempty"`
}
