/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CreateCvfss3Bucket struct {
	// The name of the CVFS S3 bucket to be created
	Name string `json:"name"`
	// Plan name to be used to fetch the CVFS S3 cluster
	PlanName string `json:"planName"`
	Versioning *CvfsVersioning `json:"versioning"`
	// The size of the bucket in GB
	BucketSize string `json:"bucketSize,omitempty"`
}
