/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Replication options for Amazon. sourceVM should contain the name and the guid of the machine that has to be overriden
type OverrideReplicationOptionsAmazonCreate struct {
	SourceVM *NameGuid `json:"sourceVM"`
	// Display name for the destination instance
	InstanceName string `json:"instanceName"`
	// The name of the AWS region where the destination instance will reside
	RegionName string `json:"regionName"`
	// The name of AWS zone where the destination instance will reside
	AvailabilityZone string `json:"availabilityZone"`
	// ID of the volume type that will be used on the destination instance. Default value is Auto
	VolumeType string `json:"volumeType,omitempty"`
	// The ID of the encryption key that will be used to encrypt the data of the desination instance. Default value is Auto
	EncryptionKey string `json:"encryptionKey,omitempty"`
	Network *NetworkVpcSubnet `json:"network,omitempty"`
	// The security group to be applied to the destination instance that acts as a virtual firewall. Default value is Auto
	SecurityGroups []SecurityGroup `json:"securityGroups,omitempty"`
	// The available CPU cores and memory to be used on the destination instance. Default value is Auto
	InstanceType string `json:"instanceType,omitempty"`
	GuestCredentials *GuestCredentialsCreate `json:"guestCredentials,omitempty"`
}
