/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Application validation source copy details
type AppValidationSourceCopy struct {
	// Id of the source copy
	Id int32 `json:"id,omitempty"`
	// Name of the source copy
	Name string `json:"name,omitempty"`
	// Is this an active backup destination?
	IsActive bool `json:"isActive,omitempty"`
	// Is this a snap copy?
	IsSnapCopy bool `json:"isSnapCopy,omitempty"`
	// Order of backup destinaion copy created in storage policy
	CopyPrecedence int32 `json:"copyPrecedence,omitempty"`
	BackupDestination *IdName `json:"backupDestination,omitempty"`
}
