/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Custom validation script to be used during VM backup validation
type AppValidationScript struct {
	Windows *ValidationScript `json:"windows,omitempty"`
	Unix *ValidationScript `json:"unix,omitempty"`
}
