/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Describes the label selector content for the Application Group
type KubernetesContentSelectors struct {
	// Value of the label selector in key=value format
	SelectorValue string `json:"selectorValue"`
	// Selector level of the label selector
	SelectorLevel string `json:"selectorLevel"`
}
