/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type ManualServerGroupAssociationDetails struct {
	// List of associated servers
	Associatedservers []IdName `json:"associatedservers,omitempty"`
}
