/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// License details
type LicenseInfo struct {
	// ID of the registered CommCell
	CommCellId int32 `json:"commCellId,omitempty"`
	// IP Address of CommServe
	CommServeIPAddress string `json:"commServeIPAddress,omitempty"`
	// IP Address of License
	LicenseIPAddress string `json:"licenseIPAddress,omitempty"`
	// The license is for this software product
	Edition string `json:"edition,omitempty"`
	// This license is intended for the specified usage scenario
	LicenseMode string `json:"licenseMode,omitempty"`
	// Serial number of CommServe
	SerialNumber string `json:"serialNumber,omitempty"`
	// Registration code of CommServe
	RegistrationCode string `json:"registrationCode,omitempty"`
	// Expiry date of current license in epoch format
	ExpiryDate int32 `json:"expiryDate,omitempty"`
}
