/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Object to suggest possible plan rule tags that can be part of plan entity rule
type PlanEntityRuleTag struct {
	// GUID for the tag
	GUID string `json:"GUID,omitempty"`
	// Id for the tag
	Id int32 `json:"id,omitempty"`
	// Name for the plan rule tag which need to be matched against tag of the workload.
	Name string `json:"name,omitempty"`
	// Possible value that need to matched against value of tag associated to workload.
	Value string `json:"value,omitempty"`
}
