/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// company-refers to company to which the blackout window is associated.Dates have to be provided in unix time format.
type V4UpdateBlackoutWindow struct {
	// Refers to the newName given to the blackout Window.
	NewName string `json:"newName,omitempty"`
	// Refers to backup types to include in the blackout window
	BackupOperations []string `json:"backupOperations,omitempty"`
	Company *IdName `json:"company,omitempty"`
	// Days of the week when the blackout window will be in effect.
	Days []DayOfTheWeek `json:"days,omitempty"`
	// Refers to the weeks of the month that the blackout window will be in effect.
	Weeks []WeekOfMonth `json:"weeks,omitempty"`
	// Refers to the time between which the blackout window will be in effect. It has to be provided in seconds
	Time []StartEnd `json:"time,omitempty"`
	BetweenDates *StartEnd `json:"betweenDates,omitempty"`
	// Allows or Denies submitting a job when the blackout window is in effect. If allowed, the job is submitted and resumed once the blackout window ends.
	DoNotSubmitJob bool `json:"doNotSubmitJob,omitempty"`
}
