/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type UpdateApplicationGroupRequest struct {
	Options *ApplicationGroupGetOptions `json:"options,omitempty"`
	Timezone *IdName `json:"timezone,omitempty"`
	ActivityControl *ApplicationGroupActivityControl `json:"activityControl,omitempty"`
	Tags []NameValue `json:"tags,omitempty"`
	// Specify new name to rename an Application Group
	Name string `json:"name,omitempty"`
	Plan *IdName `json:"plan,omitempty"`
	Content *KubernetesApplicationGroupContent `json:"content,omitempty"`
	Filters *KubernetesApplicationGroupFilters `json:"filters,omitempty"`
}
