/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type QueryAdditionalInfo struct {
	// List of query parameters
	QueryParameters []QueryParameter `json:"queryParameters,omitempty"`
}
