/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of Access Nodes
type KubernetesAccessNodes struct {
	AccessNodes []IdNameType `json:"accessNodes,omitempty"`
}
