/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// None of the fields are mandatory. whichever field is specified should be updated. Rest should be untouched.
type UpdateEmailServerReq struct {
	// The name of the mail server that sends alerts, scheduled reports, log files, and additional information.
	SMTPServerName string `json:"SMTPServerName,omitempty"`
	// The port number that connects to the mail server.
	SMTPPort int32 `json:"SMTPPort,omitempty"`
	// The sender email address used for emails sent from the software.
	SenderEmail string `json:"senderEmail,omitempty"`
	// The sender name used for emails sent from the software.
	SenderName string `json:"senderName,omitempty"`
	EncryptionAlgorithm *SmtpServerEncryptionAlgorithm `json:"encryptionAlgorithm,omitempty"`
	// The option to use authentication on the mail server. This is typically used in external or internet mail server configurations.
	UseAuthentication bool `json:"useAuthentication,omitempty"`
	// when useAuthentication is true, username must be present
	Username string `json:"username,omitempty"`
	// Password must be in base 64 encoded format. Password attribute can be left out to reuse the already saved password
	Password string `json:"password,omitempty"`
}
