/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type OracleObjectBucket struct {
	// Name of cloud vendor
	CloudType string `json:"cloudType"`
	MediaAgent *IdName `json:"mediaAgent,omitempty"`
	// IP address or fully qualified domain name or URL for the cloud library based on cloud vendor
	ServiceHost string `json:"serviceHost,omitempty"`
	Credentials *IdName `json:"credentials"`
	// OCI compartment name
	CompartmentName string `json:"compartmentName,omitempty"`
	// Name of the bucket
	Bucket string `json:"bucket"`
	// Appropriate storage class for your account
	StorageClass string `json:"storageClass"`
	// Applicable for Archive storage class only
	UseCombinedStorage bool `json:"useCombinedStorage,omitempty"`
	// Appropriate combined storage class for archive. Applicable only when useCombinedStorage is true.
	CombinedStorageClass string `json:"combinedStorageClass,omitempty"`
	// If the MediaAgent accesses the mount path using a proxy then proxy server address needs to be provided. If you want to remove proxy information, pass empty string in proxyAddress.
	ProxyAddress string `json:"proxyAddress,omitempty"`
	// Port for proxy configuration
	Port int32 `json:"port,omitempty"`
	// Username for proxy configuration
	Username string `json:"username,omitempty"`
	// Password for proxy configuration (Should be in Base64 format)
	Password string `json:"password,omitempty"`
}
