/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CredentialAccountType string

// List of CredentialAccountType
const (
	WINDOWSACCOUNT_CredentialAccountType CredentialAccountType = "WINDOWSACCOUNT"
	LINUXACCOUNT_CredentialAccountType CredentialAccountType = "LINUXACCOUNT"
	STORAGE_ARRAY_ACCOUNT_CredentialAccountType CredentialAccountType = "STORAGE_ARRAY_ACCOUNT"
	CLOUD_ACCOUNT_CredentialAccountType CredentialAccountType = "CLOUD_ACCOUNT"
)
