/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type Vmslastatus string

// List of VMSLASTATUS
const (
	ALL_Vmslastatus Vmslastatus = "ALL"
	PROTECTED_Vmslastatus Vmslastatus = "PROTECTED"
	NOT_PROTECTED_Vmslastatus Vmslastatus = "NOT_PROTECTED"
	PENDING_Vmslastatus Vmslastatus = "PENDING"
	BACKED_UP_WITH_ERROR_Vmslastatus Vmslastatus = "BACKED_UP_WITH_ERROR"
	DISCOVERED_Vmslastatus Vmslastatus = "DISCOVERED"
)
