/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type CommcellNameDisplayNameInfo struct {
	// Name of the commcell the entity belongs to.
	Name string `json:"name,omitempty"`
	// Display name of the commcell the entity belongs to.
	DisplayName string `json:"displayName,omitempty"`
}
