/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// List of permissions associated with the entity. Either categoryId and categoryName or permissionId and permissionName will be returned. If categoryId or categoryName is returned, all the corresponding permissions in the category are associated with the entity.
type PermissionResp struct {
	PermissionId int32 `json:"permissionId,omitempty"`
	PermissionName string `json:"permissionName,omitempty"`
	CategoryId int32 `json:"categoryId,omitempty"`
	CategoryName string `json:"categoryName,omitempty"`
	// Returns the type of association.
	Type_ string `json:"type,omitempty"`
	// Flag to specify if this is included permission or excluded permission.
	Exclude bool `json:"exclude,omitempty"`
}
