/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient
// CvfsVersioning : To enable/suspend the versioning on the CVFS S3 bucket
type CvfsVersioning string

// List of CVFSVersioning
const (
	UNVERSIONED_CvfsVersioning CvfsVersioning = "UNVERSIONED"
	ENABLED_CvfsVersioning CvfsVersioning = "ENABLED"
	SUSPENDED_CvfsVersioning CvfsVersioning = "SUSPENDED"
)
