/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

type DayAndTime struct {
	DayOfWeek []DayOfTheWeek `json:"dayOfWeek,omitempty"`
	// Time in seconds since the beginning of the day
	StartTime int64 `json:"startTime,omitempty"`
	// Time in seconds since the beginning of the day
	EndTime int64 `json:"endTime,omitempty"`
}
