/*
 * Commvault REST API
 *
 * Commvault APIs
 *
 * API version: LATEST
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiclient

// Gives the summary of the virtual machines.
type VirtualMachineSummary struct {
	// The display name of the VM.
	Name string `json:"name,omitempty"`
	// The hypervisor where the VM is located.
	Vendor string `json:"vendor,omitempty"`
	Hypervisor *IdName `json:"hypervisor,omitempty"`
	VmGroup *IdName `json:"vmGroup,omitempty"`
	// The operating system version for the VM or instance.
	Os string `json:"os,omitempty"`
	// The host name for the computer where the source virtual machine or instance resides.
	Host string `json:"host,omitempty"`
	// The total space allocated(in bytes) for the virtual machine.
	VmSize int32 `json:"vmSize,omitempty"`
	// The status of the backup for the VM, instance, or  container.
	Status string `json:"status,omitempty"`
	// The globally unique identifier for the VM client.
	UUID string `json:"UUID,omitempty"`
	// Name of the commcell the VM belongs
	CommcellName string `json:"commcellName,omitempty"`
	LastBackup *LastBackup `json:"lastBackup,omitempty"`
	// The amount of data being protected for the VM client(in bytes)
	ApplicationSize int32 `json:"applicationSize,omitempty"`
	Plan *PlanIdNameType `json:"plan,omitempty"`
	SLA *VmSla `json:"SLA,omitempty"`
	Company *IdName `json:"company,omitempty"`
	Tags []IdNameValue `json:"tags,omitempty"`
	Commcell *CommcellInfo `json:"commcell,omitempty"`
}
