name: CI - Build and test

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4
      - run: make build
      - run: make test