on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
  release-with-goreleaser:
    needs: release-please
    if: needs.release-please.outputs.releases_created
    secrets: inherit
    uses: ./.github/workflows/release.yaml